#pragma once
#include"Object.hpp"
#include"Boolean.hpp"
#include"BetweenValue.hpp"
#include"Char.hpp"
#include"String.hpp"
#include"Numeric.hpp"
#include"Floating.hpp"
#include"Integer.hpp"

#include"Object.inl"
#include"Boolean.inl"
#include"BetweenValue.inl"
#include"Char.inl"
#include"String.inl"
#include"Numeric.inl"
#include"Floating.inl"
#include"Integer.inl"
